pipeline{ 
agent any   
stages{
  
   /* stage('SonarQube Analysis') {
     agent any
       steps{
      
       withSonarQubeEnv( 'sonarqube') {
      sh "${scannerHome}/sonar-scanner"
          }
        }
        }*/

      
         stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'sonar-runner'
                    withSonarQubeEnv() {
                        sh "${scannerHome}/sonar-runner \

                    }
                }
            }
        }

   }
    
}
