pipeline{ 
agent any   
stages{
  
   /* stage('SonarQube Analysis') {
     agent any
       steps{
      
       withSonarQubeEnv( 'sonarqube') {
      sh "${scannerHome}/sonar-scanner"
          }
        }
        }*/

       stage('SCM') {
         steps {
            script {   
              checkout scm
             }
          }
       }
         stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'SonarQubeScanner'
                    withSonarQubeEnv() {
                        sh "${scannerHome}/sonar-scanner-debug \
  -Dsonar.projectKey=python \
  -Dsonar.sources=. \
  -Dsonar.host.url=http://172.17.0.2:9000/"
                    }
                }
            }
        }

   }
    
}
